"""Common Luanti node names (default / minetest_game style packs)."""

NODES = {
    "air": "air",
    "stone": "default:stone",
    "cobblestone": "default:cobble",
    "dirt": "default:dirt",
    "grass": "default:grass",
    "sand": "default:sand",
    "wood": "default:wood",
    "tree": "default:tree",
    "leaves": "default:leaves",
    "glass": "default:glass",
    "brick": "default:brick",
    "sandstone": "default:sandstone",
    "stonebrick": "default:stonebrick",
    "torch": "default:torch",
    "water": "default:water_source",
    "lava": "default:lava_source",
    "ice": "default:ice",
    "snow": "default:snow",
    "bookshelf": "default:bookshelf",
    "obsidian": "default:obsidian",
    "goldblock": "default:goldblock",
    "steelblock": "default:steelblock",
    "mese": "default:mese",
}

BLOCK_ICONS = {
    "air": "⬜",
    "stone": "🪨",
    "cobblestone": "🪨",
    "dirt": "🟫",
    "grass": "🌿",
    "sand": "🟨",
    "wood": "🪵",
    "tree": "🌳",
    "leaves": "🍃",
    "glass": "🪟",
    "brick": "🧱",
    "sandstone": "🟨",
    "stonebrick": "🧱",
    "torch": "🔦",
    "water": "💧",
    "lava": "🔥",
    "ice": "🧊",
    "snow": "❄️",
    "bookshelf": "📚",
    "obsidian": "🟪",
    "goldblock": "🟨",
    "steelblock": "⬜",
    "mese": "💎",
}
